name: tasbih
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  get_storage: ^2.1.1
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/beads/bead-1.png
    - assets/beads/bead-2.png
    - assets/beads/bead-3.png
    - assets/beads/bead-4.png
    - assets/beads/bead-5.png